INSERT INTO plant (name,price) VALUES ('Lavender',9.99);
INSERT INTO plant (name,price) VALUES ('Snapdragon',6.00);
INSERT INTO plant (name,price) VALUES ('Cleome',3.25);
INSERT INTO plant (name,price) VALUES ('Caladium',9.75);
INSERT INTO plant (name,price) VALUES ('Black-Eyed Susan',8.75);
INSERT INTO plant (name,price) VALUES ('Maiden Grass',12.00);
INSERT INTO plant (name,price) VALUES ('Daylily',4.50);
INSERT INTO plant (name,price) VALUES ('Yaupon Holly',30.00);
INSERT INTO plant (name,price) VALUES ('Spiraea',39.99);
INSERT INTO plant (name,price) VALUES ('Clethra',25.00);
INSERT INTO plant (name,price) VALUES ('Sourwood',69.99);
INSERT INTO plant (name,price) VALUES ('Apple',19.99);
INSERT INTO plant (name,price) VALUES ('Swamp White Oak',25.00);
INSERT INTO plant (name,price) VALUES ('Peonies',6.99);
INSERT INTO plant (name,price) VALUES ('Boxwood',19.99);
INSERT INTO plant (name,price) VALUES ('Red Twig Dogwood',32.10);
INSERT INTO plant (name,price) VALUES ('Chocolate Vine',11.99);